### ISSUE TITLE
Generalize `kgtk lower` column recognition

### ISSUE THREAD

**Issue by CraigMiloRogers** [usc-isi-i2/kgtk#176]
1) `kgtk lower` should automatically lower `;*' instead of just `;label`.
2) If an additional column doesn't fit this pattern, and there is an `id` column present, normalize the secondary edge 
    1) Perhaps this should be in a separate command, `kgtk normalize-edges`, as `kgtk lower` was intended to invert `kgtk lift`
3) Give options to automatically generate ID values for the new edges `kgtk lower` generates.

**Comment by szeke** [comment]
I think lift should be generic too. Let's use the word relation for `node1/relation/node2` so we don't get confused with the ambiguous meaning of `label`.

The `lift` command should accept a list of symbols that can appear in the relation column and lift them as headers. 

Suppose I have edges as:

```
id1/n1/rel/o1
id2/n2/rel/o2
id3/id1/rel/o3
```

We will get 3 new columns:

- `node1;rel`
- `node2;rel`
- `rel`

The above 3 edges will disappear from the file because we are lifting `rel`. Where will the info go?

`o1` goes in `node1;rel`, `o2` goes in `node1;rel`, `o3` goes in `rel`

@CraigMiloRogers agreed?

**Comment by CraigMiloRogers** [comment]
Yes.  Right now there are some expert options to `kgtk lift`, but they don't work quite as well as what you described.

**Comment by CraigMiloRogers** [comment]
Generalized lowering and normalization changes have been committed. ID generation is still pending.

**Comment by CraigMiloRogers** [comment]
I split the ID generation into a separate issue.
