### ISSUE TITLE
Write command to combine edges and qualifier files

### ISSUE THREAD

**Issue by szeke** [usc-isi-i2/kgtk#192]
The `combine-with-qualifiers` command should take two files as input:

- An `input` edge file containing arbitrary edges. This command treats all edges in the input file as top edges.
- A `qualifier` file, where the `node1` symbols match ids in the edge file. It is possible that some `node1`s in the qualifier file have no corresponding `id` in the edge file.

The output is a single file that combines the edge file and the qualifier file with the edges sorted as follows:

- All edges in the `qualifier` file must follow the edge in the `input` file where `input.id = qualifier.node1`. Within this group, the qualifier edges should be sorted by `node1/label/node2`
- The order of edges in the `input` file can be changed, but all columns of the input file should be preserved.
- Edges in the `qualifier` file that do not have a corresponding edge in the `input` file should be discarded. Provide an option to write them to a rejects file.

The command should work with limited memory, so it is not allowed to build a dictionary of all edges in the qualifier file. Instead, the command should use sorting and possibly multiple passes to operate with finite memory.

One option is to do the following:

- sort the `input` file by `id/node1/label/node2`
- sort the `qualifier` file by `node1/id`
- stream the two files simultaneously, for each edge in the input file, all the qualifier edges in the `qualifier` file will be contiguous.

Files to test are present in https://drive.google.com/open?id=1rALbIXCAP54HWtkEBbz7z2fg5Cnzx-TY&authuser=szekely%40usc.edu&usp=drive_fs (accessible only at ISI)

**Comment by dgarijo** [comment]
I guess this is for the wikidata import command (just adding a description because there is none)

**Comment by CraigMiloRogers** [comment]
They way the current system works is this:
- the top edge records, which I'm currently calling "claim edges", have an ID that is composed of a particular pattern.
  - the id pattern starts with node1 and label, then has either the node 2 value if the node2 value is Qxxx or Pxxx, or it has a hash of the node2 value.
  - This is followed by the claim hash, rehashed, followed by a decollision counter.
- The qualifier records have the claim edge ID in their node1 field, and have an id value that starts with the claim edge ID, then adds the qualifier record's label, then the qualifier record's node2 value (if Qxxx or Pxxx) or hash, then a decollision counter (I'm going by memory, so I might be slightly off).
- Both the claim and the qualifier records are sorted by their ID fields. The other fields (node1, label, node2) aren't really relevant because the ID field contains copies, and I'm thinking of dropping them from the sort commands, which should speed up the sort commands.
  -- But, becahse the ID field may contain a hash of the node2 value, sorting by id is not exactly the same as sorting by node1/label/node2.
-- The claim records and the qualifier records may be combined with `kgtk cat` and sorted with `kgtk sort2`.  This should clump the claim records and their qualifier records together
  - I think a claim record should be followed by its qualifiers, but I can't be certain.

**Comment by CraigMiloRogers** [comment]
If you want to subset the qualifier edges to just the ones that appear in the claims edges, that can be done with `kgtk ifexists --presorted` so long as both input files are sorted on the `id` field.
 - The qualifier file is supposed to be sorted on the node1 field, but since the id field begins with the node1 field's value, there's no difference.

**Comment by CraigMiloRogers** [comment]
There are examples of this `kgtk ifexists` pattern in the latter part of the `partition-wikidata` Jupyter notebook (the most recent version of which is `partition-wikidata-language-regex`).  I've just pushed the latest updates into the `dev` branch.

**Comment by CraigMiloRogers** [comment]
The purpose of this command is to prepare files for exporters that require that qualifiers immediately follow the edges they qualify, *without* imposing constraints on the patterns used for IDs.

**Comment by CraigMiloRogers** [comment]
Pedro says this is for loading data into the SPARQL endpoint. Perhaps we should map the datatypes as an option.

**Comment by szeke** [comment]
There is no need to worry about the datatypes, as there is a small file of datatypes, and the RDF generator can read the external file

**Comment by CraigMiloRogers** [comment]
@szeke Is the output of this program to be consumed by `kgtk generate-wikidata-triples` or by something else? (If something else, what?) I want to be certain I understand what the output format can be, and can test that the output of the new program is acceptable input to the next program.

**Comment by szeke** [comment]
This command should be generic, so its output can be used in any other command. It should contain id/node1/label/node2, as this may be the only info you get as input.

**Comment by CraigMiloRogers** [comment]
I've tested `examples/combine-with-qualifiers.ipynb` with the test files @szeke supplied, and skimmed through a little of the output file.  It looks OK to me. @szeke , are you satisfied with it?

**Comment by CraigMiloRogers** [comment]
Closing, since the script appears to meet the specification.
