### ISSUE TITLE
`kgtk add-id` Hashed Node2

### ISSUE THREAD

**Issue by CraigMiloRogers** [usc-isi-i2/kgtk#244]
Add options to use a hashed node2 value, and optionally include the Wikidata-supplied hash, in the same style as `kgtk import-wikidata` now uses.

**Comment by CraigMiloRogers** [comment]
@saggu asserts that this feature is needed for Wikidata OS deployment.

**Comment by szeke** [comment]
Just to be clear, the requirement is to sort main edges in qualifier edges so that the qualifier edges follow the edge they qualify, so that Wikidata OS works.

This issue may be redundant as the goal it generate the triples, and if we can get the files sorted properly, we don't need this type of id.

**Comment by CraigMiloRogers** [comment]
The merge script, `examples/combine-with-qualifiers.ipynb`, assumes:

1. The claims rows have an ID value.
2. Claims row ID values are unique.
3. Each qualifier row node1 value matches a claim row ID value.
4. There may be multiple qualifier rows matching a single claim row.

It doesn't matter to `examples/combine-with-qualifiers.ipynb` how the ID values are generated, so long the constraints listed above are met.

**Comment by CraigMiloRogers** [comment]
`kgtk add-id` has been updated with `--id-style wikidata` and `--id-style wikidata-with-claim-id`.
