### ISSUE TITLE
The package `sh` is not available on windows

### ISSUE THREAD

**Issue by saggu** [usc-isi-i2/kgtk#368]
People developing code on Windows are not able to install `kgtk` due to the package `sh` not being available on windows.

This scenario is different than using docker, because kgtk is installed as a package in another python FLASK API.

Is it possible to remove the package `sh` and use an alternative ?

**Comment by chalypso** [comment]
It would be possible to replace sh, but it is a significant undertaking since it is used in quite a lot of functionality.  It would be fairly easy to replace it for query, but it is also used quite extensively for sort, cat, cli pipes, exceptions, plus this seems to go into the direction of fully supporting KGTK under Windows which opens a completely separate can of worms.  So I'd rather not go this route unless there is a very strong case for it.

**Comment by saggu** [comment]
Closing, not relevant anymore
