### ISSUE TITLE
Edges inference for inverse and simetric properties

### ISSUE THREAD

**Issue by versant2612** [usc-isi-i2/kgtk#392]
**Is your feature request related to a problem? Please describe.**
Edges creation from inverse properties and specification of symmetric properties that allow bidirectional analysis of the relations without transforming the whole graph into non-directed

**Describe the solution you'd like**
I solved my case with these steps

kgtk filter -i input.tsv -p " ; dcterms:isReferencedBy ; " -o output-inverse.tsv
edit output-inverse.tsv header to interchange node1 and node2
sed -i 's/dcterms:isReferencedBy/dcterms:references/g' output-inverse.tsv
kgtk cat -i input.tsv output-inverse.tsv -o output-all.tsv

I would like something like 

kgtk <inverse operation> --inverse-properties "dcterms:isReferencedBy ; dcterms:references" -i input.tsv -o output.tsv

**Describe alternatives you've considered**

Or new options in existing kgtk commands like 

kgtk <paths, recheable_nodes, graph_statistics > --inverse-properties-file inverse.tsv --symmetric-properties "n1:hasSibling" -i input.tsv -o output.tsv

node1   label     node2
dcterms:isReferencedBy   inverse_properties    dcterms:references

**Comment by szeke** [comment]
It is possible to do the transformations using `kgtk query` as follows, I will show an example using Wikidata properties. Because dbpedia properties have colon there is a need to quote the values.

```
kgtk query -i <file> --graph-cache ... \
--match '(n1)-[:P123]->(n2)'  \
--return 'n2 as node1, "P123_inverse" as label, n1 as node2' \
--order-by 'n2, label'
```

A similar query can be used to do the symmetric properties.

It is possible to complete the graph with all the inverse and symmetric properties in one command. We need to define edges for the properties to record their inverses, and to record whether they are symmetric. Then a single query can do all of them:

```
kgtk query -i <file> --as input -I <properties-file> --as properties --graph-cache ... \
--match '\
    properties: (prop)-[:inverse]->(prop_inv) \
    input: (n1)-[l {label: prop}]->(n2)'  \
--return 'n2 as node1, prop_inv as label, n1 as node2' \
--order-by 'n2, label, n1'
```
The above assumes that the <properties-file> has edges of the form <property, inverse, inverse_property>

**Comment by versant2612** [comment]
@szeke Thanks. It worked exactly as you explained.
