### ISSUE TITLE
Increase `kgtk cat` Performance

### ISSUE THREAD

**Issue by CraigMiloRogers** [usc-isi-i2/kgtk#613]
Increase the performance of `kgtk cat` when possible.

Requested by @szeke.

**Comment by CraigMiloRogers** [comment]
`kgtk cat` already benefits by fast path speedups.  When various conditions are met (the column headers are the same, input data is not being validated, etc.), a line-by-line Python copy is performed which does not parse the data columns.

**Comment by CraigMiloRogers** [comment]
It should be possible to use OS commands to copy the files the way that `kgtk sort` operates.  It might be difficult to do this if the input files are compressed... we'll probably have to use a stdout append.

Dynamically transitioning between the system approach and the more-capable Python approach would be difficult. Initially, I'd want to use an option that asserts that the system approach should be used, aborting if the files headers don't match.

**Comment by CraigMiloRogers** [comment]
Using the OS tools to concatenate the KGTK files when columns need to be shuffled is more difficult.  The `cut` and `paste` commands provide a starting point.  We need a way to create blank columns:  `sed`? `awk`?

**Comment by CraigMiloRogers** [comment]
Another approach to the column shuffle is to use `awk`.  For example, see:

https://www.unix.com/shell-programming-and-scripting/217879-insert-empty-columns-flat-file.html

**Comment by CraigMiloRogers** [comment]
Another approach to explore is to use C code to perform the high-performance `kgtk cat` operation.  We could supply an extension that loads into Python, or a C program that is called through our OS interface.

**Comment by szeke** [comment]
Comparison of kgtk-cat, zcat and cat on my machine. Ran all the commands once, and then ran them again, so that the files are cached, etc.
![image](https://user-images.githubusercontent.com/1074599/150878209-6b950011-7ee6-4491-81fb-8fdf971f2722.png)

Cat is much faster than kgtk-cat. Maybe just want to optimize the case that all the files have the exact same headers  (in the same order), using the system commands in such cases. 

Also, a possible simple optimization is that the first file dictates the headers, and it is copied out using a system command (cat/zcat). Subsequent files are written out using system commands if they conform to the headers of the first file, and using the current scheme, if they don't.

**Comment by CraigMiloRogers** [comment]
After thinking about it a bit, if none of the input files are standard input (or named files descriptors), then we should be able to open and read each file more than once.  In that case, `kgtk cat` could open all the files in Python code and decide whether or not it should be possible to attempt an OS tool.

**Comment by CraigMiloRogers** [comment]
There should be an option to force a pure Python solution, as there s with `kgkt sort`.

Possibly, the Python code should look at the size of each input file, and use a pure Python solution if the total file size is small.

**Comment by CraigMiloRogers** [comment]
Code changes merged into `dev`. Documentation changes pending.

**Comment by CraigMiloRogers** [comment]
Documentation pushed into `dev`.
